language: php

php:
  - 5.3
  - 5.4

env:
  - TRANSPORT=jackrabbit
#  - TRANSPORT=doctrine-dbal
  - TRANSPORT=midgard_sqlite
  - TRANSPORT=midgard_mysql

before_script:
  # first always install midgard as its required for composer.phar install --dev
  - ./tests/travis_midgard_install.sh
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - ./tests/travis_${TRANSPORT}.sh

script: phpunit -c tests/phpunit_${TRANSPORT}.xml.dist

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
